version: '3'
volumes:
  db:
  storage:

services:
  welp:
    container_name: welp
    volumes:
      - db:/db
      - storage:/storage
    restart: always
    ports:
      - 80:80
      - 443:443
    image: zlepper/welp
    command: /usr/bin/welp --useHttps
